image: node:12-alpine

.deploy: &deploy
  - echo API_URL=$API_URL >> .env.production
  - echo API_KEY_MAPS=$API_KEY_MAPS >> .env.production
  - npm install -g firebase-tools
  - npm install -g @quasar/cli
  - npm install

stages:
  - testing
  - production

testing:
  stage: testing
  before_script:
    - *deploy
  only:
    - develop
  environment:
    name: develop
  variables:
    ENVIRONMENT: develop
  script:
    - npm run build-pwa
    - firebase use ikiero-test --token $FIREBASE_TOKEN_TEST
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:manage-test --non-interactive --token $FIREBASE_TOKEN_TEST

production:
  stage: production
  before_script:
    - *deploy
  only:
    - master
  environment:
    name: production
  variables:
    ENVIRONMENT: production
  script:
    - npm run build-pwa
    - firebase use ikiero --token $FIREBASE_TOKEN
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:manageikiero-prod --non-interactive --token $FIREBASE_TOKEN
